---

- name: composrのインストールスクリプトをダウンロード
  get_url:
    url: https://getcomposer.org/installer
    dest: /home/dev-user/composer-setup.php
- name: composrのインストール
  become: true
  shell: php /home/dev-user/composer-setup.php --install-dir=/usr/local/bin --filename=composer
