---

- name: minioユーザー追加
  user:
    name: minio-user
    shell: /sbin/nologin
- name: データ保存用ディレクトリ作成
  become: true
  file:
    path: /var/minio/s3/
    state: directory
    mode: 0777
- name: ダウンロード
  become: true
  get_url:
    url: https://dl.minio.io/server/minio/release/linux-amd64/minio
    dest: /usr/local/bin/minio
- name: 実行権限付与
  become: true
  file:
    path: /usr/local/bin/minio
    mode: u+x,g+x,o+x
- name: サービス起動スクリプトダウンロード
  become: true
  get_url:
    url: https://raw.githubusercontent.com/minio/minio-service/master/linux-systemd/minio.service
    dest: /etc/systemd/system/minio.service
- name: 設定ファイルコピー
  become: true
  copy:
    src: settings
    dest: /etc/default/minio
- name: minioサービス有効化と起動
  become: true
  systemd:
    name: minio.service
    state: restarted
    daemon_reload: yes
    enabled: yes
