---

- name: nginxのインストール
  become: true
  apt:
    name: nginx
    state: present
    update_cache: yes
- name: システム設定ファイルのコピー
  become: true
  copy:
    src: nginx.conf
    dest: /etc/nginx/
    owner: root
    group: root
    mode: 644
- name: サイト設定ファイルのコピー
  become: true
  copy:
    src: default
    dest: /etc/nginx/sites-available/
    owner: root
    group: root
    mode: 644
- name: /var/www/htmlの所有者とパーミッションを変更
  file:
    path: /var/www/html
    state: directory
    recurse: yes
    mode: 777
    owner: dev-user
    group: dev-user
- name: phpinfo()を表示するファイルをコピー
  copy:
    src: info.php
    dest: /var/www/html/
    owner: dev-user
    group: dev-user
    mode: 644
- name: 起動
  become: true
  systemd:
    name: nginx
    state: restarted
    daemon_reload: yes
    enabled: yes
