---

- name: 公開鍵を登録
  authorized_key:
    user: dev-user
    state: present
    key: https://github.com/{{ item.name }}.keys
  with_items:
    - "{{ users }}"
- name: 必要になるパッケージをインストール
  become: true
  apt:
    state: present
    name:
      - lsb-release
      - apt-transport-https
      - ca-certificates
      - wget
      - curl
    update_cache: yes
